create table if not exists whop_installations (
  id bigint generated by default as identity primary key,
  community_id text not null,
  member_id text unique not null,
  access_token text not null,
  refresh_token text not null,
  expires_at timestamp with time zone not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Add RLS (Row Level Security) policies
alter table whop_installations enable row level security;

-- Allow authenticated users to view their installations
create policy "Whop installations are viewable by authenticated users."
  on whop_installations for select using (auth.uid()::text = member_id);

-- Allow members to insert their own installations
create policy "Members can insert their own whop installations."
  on whop_installations for insert with check (auth.uid()::text = member_id);

-- Allow members to update their own installations
create policy "Members can update their own whop installations."
  on whop_installations for update using (auth.uid()::text = member_id);

