create table if not exists dm_templates (
  id bigint generated by default as identity primary key,
  community_id text not null,
  name text not null,
  steps jsonb default '[]'::jsonb not null,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

-- Add RLS (Row Level Security) policies
alter table dm_templates enable row level security;

-- Allow authenticated users to view templates for their community
create policy "DM templates are viewable by authenticated users of their community."
  on dm_templates for select using (auth.uid()::text = community_id); -- Assuming community_id maps to auth.uid for simplicity

-- Allow community owners to insert their own templates
create policy "Community owners can insert their own DM templates."
  on dm_templates for insert with check (auth.uid()::text = community_id);

-- Allow community owners to update their own templates
create policy "Community owners can update their own DM templates."
  on dm_templates for update using (auth.uid()::text = community_id);
